// BITE.co Frontend Configuration — auto-generated by Terraform
// Do NOT edit this file manually; edit frontend/config.js.tpl instead.
const API_BASE_URL = 'https://${api_gw_url}';

const CONFIG = {
  API_BASE_URL,
  AUTH_URL:      `$${API_BASE_URL}/auth`,
  USUARIOS_URL:  `$${API_BASE_URL}/projects`,
  CLOUD_URL:     `$${API_BASE_URL}/cloud`,
  REPORTES_URL:  `$${API_BASE_URL}/events`,
  SEGURIDAD_URL: `$${API_BASE_URL}/security`,
};
